core/urls.py
from core import views
from django.urls import path

app_name = 'core'

urlpatterns = [
    path('play/', views.index, name='index'),
    path('answer/', views.answer, name='answer'),
    path('search/', views.search, name='search'),
    path('notifications/', views.notifications, name='notifications'),
    path('toggle-mode/', views.toggle_mode, name="toggle"),
    path('color-mode/', views.color_mode_toggle, name="color_mode"),
    path('profile/<username>/', views.profile, name='profile'),
    path('settings/', views.settings, name='settings'),
]

elementary/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from core.models import Customize, QuizTakers


elementary = Customize.objects.all()[0]
ranks = QuizTakers.objects.filter(user__user__is_staff=False).order_by("-correct_answers")
top_ranks = ranks[:3]
rest_ranks = ranks[3:]

extra_context = {
    'elementary': elementary,
    'top_ranks': top_ranks,
    'rest_ranks': rest_ranks
}

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('oauth/', include('social_django.urls', namespace='social')),
                  path('',
                       auth_views.LoginView.as_view(extra_context=extra_context), name='auth_login'),
                  path('accounts/', include('registration.backends.simple.urls')),
                  path('', include('core.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/forms.py
from django import forms
from core.models import Contactus, UserProfile


class ContactusForm(forms.ModelForm):
    """
    Contact us form template
    """

    name = forms.CharField(help_text="Enter your name", max_length=25, required=True, widget=forms.TextInput(attrs={
        'class': 'form-control input-box',
        'placeholder': 'Tell us your name'
    }))
    email = forms.EmailField(help_text="enter your mail", max_length=30, required=True, widget=forms.TextInput(attrs={
        'class': 'form-control input-box',
        'placeholder': 'Email'
    }))
    subject = forms.CharField(help_text="Enter Subject", max_length=50, required=True, widget=forms.TextInput(attrs={
        'class': 'form-control input-box',
        'placeholder': 'Subject'
    }))
    comments = forms.CharField(required=True, max_length=1000, widget=forms.TextInput(attrs={
        'class': 'form-control input-box',
        'placeholder': 'Write to us'
    }))

    class Meta:
        model = Contactus
        exclude = ('created',)


class UserProfileForm(forms.ModelForm):
    """
    UserProfile customization form
    """
    gender = forms.CharField(required=True, max_length=25)
    picture = forms.ImageField(required=False)
    department = forms.CharField(required=True, max_length=10)
    year = forms.CharField(required=True, max_length=10)
    college = forms.CharField(required=True, max_length=60)

    class Meta:
        model = UserProfile
        exclude = ('user', 'clear', 'is_previously_logged', 'color_mode', 'dark_mode',)

core/views.py
from django.shortcuts import render, HttpResponse, redirect, reverse
from core.models import Level, UserProfile, QuizTakers, Answer, Response, LevelPublish, Notification, Goodie, Customize
from django.contrib.auth.models import User
from core.forms import ContactusForm, UserProfileForm
from django.db.models import Q
from django.contrib import messages
import json
from random import randint


COLOR = {
        'purple': 'purple',
        'orange': 'orange',
        'blue': 'blue',
        'teal': 'teal',
        'yellow': 'yellow',
        'red': 'red'
    }

def index(request):
    """

    :param request:
    :return:

    Homepage rendering
    Leaderboard update
    Contact us form
    """

    context_dict = {}

    levels = Level.objects.order_by("created")

    try:
        user = User.objects.get(username=request.user.username)
        userprofile = UserProfile.objects.get_or_create(user=user)[0]
        quiztaker = QuizTakers.objects.get_or_create(user=userprofile)[0]
        loop = range(1, quiztaker.correct_answers + 1)

        context_dict["userprofile"] = userprofile
        context_dict["quiztaker"] = quiztaker
        context_dict["loop"] = loop
        context_dict["dark_mode"] = userprofile.dark_mode
        context_dict["color_mode"] = userprofile.color_mode

        if userprofile.is_previously_logged:
            all_levelpublish = LevelPublish.objects.filter(userprofile=userprofile)[::-1]
            context_dict["all_levelpublish"] = all_levelpublish

            all_levelpublish = LevelPublish.objects.filter(userprofile=userprofile)
            first_levelpublish = all_levelpublish[0]

            if not first_levelpublish.publish:
                first_levelpublish.publish = True
                first_levelpublish.save()

    except User.DoesNotExist:
        pass

    ranks = QuizTakers.objects.filter(user__user__is_staff=False).order_by("-correct_answers")
    top_ranks = ranks[:3]
    rest_ranks = ranks[3:]

    context_dict['top_ranks'] = top_ranks
    context_dict['rest_ranks'] = rest_ranks

    form = ContactusForm()
    if 'contact' in request.POST:
        form = ContactusForm(request.POST)

        if form.is_valid():
            form.save()

            return HttpResponse(
                json.dumps({'status': "Congratulation", 'message': "Submitted"}), content_type="application/json"
            )
        else:
            print(form.errors)
            return HttpResponse(
                json.dumps({'status': "Error", 'message': "Try again"}), content_type="application/json"
            )

    value = randint(1, 2)

    notifications = Notification.objects.order_by("-pub_date")
    goodies = Goodie.objects.all()
    elementary = Customize.objects.all()[0]

    context_dict["notifications"] = notifications
    context_dict["value"] = value
    context_dict["levels"] = levels
    context_dict["form"] = form
    context_dict["goodies"] = goodies
    context_dict["elementary"] = elementary

    return render(request, "core/index.html", context=context_dict)


def answer(request):
    """

    :param request:
    :return:

    Check answers, update level cleared and publish next level.
    """
    try:
        user = User.objects.get(username=request.user.username)
    except User.DoesNotExist:
        ip = request.META.get('HTTP_X_REAL_IP')
        messages.info(request, f"Don' try this. Remember, we can track your IP {ip} :)")
        return redirect('core:index')

    userprofile = UserProfile.objects.get_or_create(user=user)[0]
    quiztaker = QuizTakers.objects.get_or_create(user=userprofile)[0]

    if request.method == 'POST':

        level_no = int(request.POST['level_no'])
        current_level = Level.objects.get(number=level_no)
        level_answer = Answer.objects.get(level=current_level)
        ans = request.POST['answer']

        if str(ans).lower() == level_answer.text:

            if not current_level.is_last:
                next = Level.objects.get_or_create(number=(level_no + 1))[0]

            else:
                next = Level.objects.get(number=99)

            levelpublish = LevelPublish.objects.get_or_create(userprofile=userprofile, level=next)[0]
            levelpublish.publish = True
            levelpublish.save()

            quiztaker.correct_answers = quiztaker.correct_answers + 1

            userprofile.clear = userprofile.clear + 1
            userprofile.save()

            response = Response.objects.get_or_create(quiztaker=quiztaker, level=current_level, answer=level_answer)[0]
            response.save()

            if current_level.is_last:
                quiztaker.completed = True
                messages.success(request, f"You cleared final level. Check out the leaderboards!",
                                 extra_tags='last_level')
            else:
                messages.success(request,
                                 f"You cleared level {level_no + 1}. Keep up and be on the top of leaderboards!",
                                 extra_tags='normal_level')

            quiztaker.save()
            # return HttpResponse(
            #     json.dumps({'status': "success"}), content_type="application/json"
            # )
        else:
            messages.warning(request, f"Your answer {ans} is wrong. Think harder!")
    return redirect('core:index')


def settings(request):
    """

    :param request:
    :return:

    Initialize core for first time logged in user.
    """
    context_dict = {}


    try:
        user = User.objects.get(username=request.user.username)
    except User.DoesNotExist:
        return redirect('core:index')

    userprofile = UserProfile.objects.get_or_create(user=user)[0]
    context_dict['userprofile'] = userprofile

    if userprofile.is_previously_logged:
        try:
            levels = Level.objects.order_by("created")
            for level in levels:
                new_levelpublish = LevelPublish.objects.get_or_create(userprofile=userprofile, level=level)
                if new_levelpublish[1]:
                    new_levelpublish[0].publish = False
                    new_levelpublish[0].save()
        except:
            print("Levels not added")
        return redirect('core:index')

    else:
        try:
            levels = Level.objects.order_by("created")
            for level in levels:
                levelpublish = LevelPublish.objects.get_or_create(userprofile=userprofile, level=level)[0]
                levelpublish.publish = False
                levelpublish.save()
                userprofile.clear = 0
                userprofile.save()

                first_level = levels.first()
                first_level.publish = True
                first_level.save()

                all_levelpublish = LevelPublish.objects.filter(userprofile=userprofile)
                first_levelpublish = all_levelpublish[0]
                first_levelpublish.publish = True
                first_levelpublish.save()
        except:
            print("Levels not added")

    userprofile.is_previously_logged = True
    # userprofile.save()

    form = UserProfileForm()
    if request.method == 'POST':
        form = UserProfileForm(request.POST, request.FILES, instance=userprofile)

        if form.is_valid():
            form.save()
            print(request.POST.get('firstname'))
            user.first_name = request.POST.get('firstname')
            user.last_name = request.POST.get('lastname')
            user.save()
            print(user.first_name)

            return redirect('core:index')
        else:
            print(form.errors)

    return render(request, 'core/settings.html', context=context_dict)


def profile(request, username):
    """

    :param request:
    :param username:
    :return:

    Personal Profile page
    """

    user = User.objects.get(username=username)
    userprofile = UserProfile.objects.get(user=user)
    quiztaker = QuizTakers.objects.get(user=userprofile)
    loop = range(1, quiztaker.correct_answers + 1)

    try:
        current_userprofile = UserProfile.objects.get(user=request.user)
        dark_mode = current_userprofile.dark_mode
        color_mode = current_userprofile.color_mode
    except:
        dark_mode = True
        color_mode = 'yellow'

    goodies = Goodie.objects.all()
    elementary = Customize.objects.all()[0]

    context_dict = {
        'quiztaker': quiztaker,
        'loop': loop,
        'dark_mode': dark_mode,
        'color_mode': color_mode,
        'goodies': goodies,
        'elementary': elementary
    }
    return render(request, 'core/profile.html', context=context_dict)


def search(request):
    """

    :param request:
    :return:

    AJAX search for players
    """
    if request.user.is_authenticated:
        if request.method == 'POST':
            query = str(request.POST['query'])
        else:
            query = ""

        result_profiles = UserProfile.objects.filter(user__is_staff=False).filter(Q(user__first_name__contains=query) |
                                                                                  Q(user__username__contains=query) | Q(
            user__email__contains=query))
        context = {
            "result_profiles": result_profiles
        }
    else:
        ip = request.META.get('REMOTE_ADDR')
        messages.info(request, f"Bakchodi nai. Remember, I can track your IP {ip} :)")
        return redirect('core:index')

    return render(request, 'core/search.html', context=context)


def notifications(request):
    notifications = Notification.objects.order_by("-pub_date")
    context = {
        'notifications': notifications
    }
    return render(request, 'core/notifications.html', context=context)


def toggle_mode(request):
    """

    :param request:
    :return:

    Saves the dark/white mode preference
    """
    if request.user.is_authenticated:
        if request.method == 'POST':
            mode = str(request.POST['dark_mode'])
        else:
            mode = ""

templates/core/notifications.html
      {% for notification in notifications %}
      <div class="card-body">

        <h5 class="card-title">{{ notification.admin.username }} says —</h5>
        <p class="card-text">{{ notification.message }}</p>
        <p class="card-text"><small class="text-muted">posted {{ notification.whenpublished }}.</small></p>

      </div>
      <hr>
      {% endfor %}

templates/core/search.html
{% if result_profiles.count > 0 %}
{% for userprofile in result_profiles %}
<!-- Item 01 -->
<div class="col-lg-4 portfolio-item seo">
    <div class="image-border">
        <div class="portfolio-item-content">
            <img src="{{ userprofile.picture.url }}" alt="{{ userprofile.user.username }} photo" class="img-fluid">
            <div class="img-overlay text-center">
                <div class="img-overlay-content">
                    <div class="portfolio-icon">
                        <a href="{% url 'core:profile' userprofile.user.username %}"><button type="button" ><i class="lni-user"></i></button></a>
                        <a href="{{ userprofile.picture.url }}" class="js-zoom-gallery">
                            <i class="lni-zoom-in"></i>
                        </a>
                    </div>
                    <h5 class="mt-3 mb-0">{{ userprofile.user.username }}</h5>
                </div>
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% else %}

    <div class="col-lg-4 text-left mt-4">
        <div class="services-item box-hover-border">

            <div class="services-content m-4 text-center"><h5 class="mb-3">Not Available</h5>
            </div>
        </div>
    </div>

{% endif %}

templates/core/settings.html
<!--
Developed by: Gurtej Singh Rehal ( ͡° ͜ʖ ͡°)
Jalpaiguri Government Engineering College
-->
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Elementary - Complete your Profile</title>

    <link rel="shortcut icon" href="{% static 'images/t20_main/t20-logomark-black.ico' %}" type="favicon.png" />

            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <style>
    @import url(https://fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,400,300,700);
@import url(https://fonts.googleapis.com/css?family=Dosis:300,400,700);

.shadow {
  box-shadow: 0 10px 20px rgba(0,0,0,0.19), 0 6px 6px rgba(0,0,0,0.23);
}

.section-title{
    font-family:"Dosis";
    margin-bottom: 15px;
    font-size: 25px;
    font-weight: 400;
    text-transform: uppercase;
    text-align: center;
    letter-spacing: 0.5em;
    line-height: 1.4;
}

.font-alt1{
    font-family:"Dosis";
    text-transform: uppercase;
    letter-spacing: 0.3em;
    line-height: 1.4;
    font-weight: 400;


}

.font-alt{
    font-family:"Dosis";
    text-transform: uppercase;
    font-weight: 700;
}

        body{
            overflow-x: hidden;
            background: #202020 !important;
        }
    </style>
    <!-- Plugin Css -->
        <link rel="stylesheet" href="{% static 'css/elementary/plugins.css' %}">
        <!-- Colors Css -->
        <link rel="stylesheet" href="{% static 'css/elementary/color/yellow-color.css' %}" id="option-color">
        <!--  Custom Style CSS  -->
        <link rel="stylesheet" href="{% static 'css/elementary/style.css' %}">
</head>
<body>



<div class="row justify-content-center" style="transform: translateY(30%)">

    <div class="col-md-4">

        <div class="card shadow box-border" style="">
            <div class="card-body ">
            <form action="{% url 'core:settings' %}" method="post" enctype="multipart/form-data">

    {% csrf_token %}
                            <div class="row font-alt">
                                <div class="form-group col-md-6">
                                    <label for="firstname">First Name</label>
                                    <input type="text" name="firstname" class="form-control" id="firstname" aria-describedby="emailHelp">
                                  </div>
                                  <div class="form-group col-md-6">
                                    <label for="lastname">Last Name</label>
                                    <input type="text" name="lastname" class="form-control" id="lastname">
                                  </div>


                            </div>

                            <div class="row font-alt mt-4">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="gender">Select your gender</label>
                                    <select name="gender" id="gender" class="form-control" required>
                                        <option>Male</option>
                                        <option>Female</option>
                                        <option>Transgender</option>
                                      </select>

                                  </div>
                                </div>

                                <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="picture">Upload Your Profile Picture</label>
                                            <input type="file" name="picture" class="form-control-file" id="picture">
                                          </div>
                                </div>

                            </div>

                                <div class="row">
                                    <div class="col-lg-6 form-item font-alt mt-4">
                                            <div class="form-group" >
                                                <label for="department">Select your Department</label>
                                                  <select name="department" id="department" class="form-control" required>
                                                    <option>IT</option>
                                                    <option>CSE</option>
                                                    <option>ECE</option>
                                                    <option>CE</option>
                                                    <option>ME</option>
                                                    <option>EE</option>

                                                  </select>

                                            </div>
                                        </div>

                                    <div class="col-lg-6 form-item font-alt">
                                            <div class="form-group">
                                                <label for="department">Select your Year</label>
                                                  <select name="year" id="year" class="form-control" required>
                                                    <option>Freshie</option>
                                                    <option>2nd</option>
                                                    <option>3rd</option>
                                                    <option>Godfather</option>
                                                    <option>Alumni</option>
                                                  </select>
                                            </div>
                                            </div>

                                </div>




                                        <div class="col-lg-12 form-item font-alt" >
                                            <div class="form-group">
                                                <label for="college">Enter your College Name</label>
                                                <input name="college" id="college" type="text" class="form-control" placeholder="College" required>
                                            </div>
                                        </div>
            <div class="row justify-content-center">
                <div class="col-md-4">
                    <input class="btn btn-dark mb-4 font-alt" type="submit" >
                </div>
            </div>

    </form>

            </div>



        </div><!--cardend-->
    </div>


</div>



<script src="{% static 'js/elementary/jquery-3.4.1.min.js' %}"></script>
<script src="https://cdn.js' %}delivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

<script>
$("#year").change(function() {
  if ($(this).val() == "Jolumni") {
    $('#college').attr('type', 'hidden');
    $('#college').attr('value', 'JGEC');
  } else {
    $('#college').attr('type', 'text');
    $('#college').attr('value', '');
  }
});
$("#year").trigger("change");
</script>

</body>
</html>